Asp.net Core MVC GestionMag/Models/Article.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.net_Core_MVC_GestionMag.Models
{
    public class Article
    {
        [Key]
        public int Id { get; set; }
        public string NomArticle { get; set; }
        public string DescriptionArticle { get; set; }
        public int QtiteArticle { get; set; }

    }
}

Asp.net Core MVC GestionMag/Models/ErrorViewModel.cs
namespace Asp.net_Core_MVC_GestionMag.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.net Core MVC GestionMag/Controllers/ArticleController.cs
using Asp.net_Core_MVC_GestionMag.Data;
using Asp.net_Core_MVC_GestionMag.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.net_Core_MVC_GestionMag.Controllers
{
    public class ArticleController : Controller
    {
        private readonly DbContextMag _db;
        public ArticleController(DbContextMag db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Article> obtArt = _db.Articles;
            return View(obtArt);
        }
    }
}

Asp.net Core MVC GestionMag/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asp.net_Core_MVC_GestionMag.Data;
using Asp.net_Core_MVC_GestionMag.Models;

namespace Asp.net_Core_MVC_GestionMag.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly DbContextMag _context;

        public ArticlesController(DbContextMag context)
        {
            _context = context;
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
              return _context.Articles != null ? 
                          View(await _context.Articles.ToListAsync()) :
                          Problem("Entity set 'DbContextMag.Articles'  is null.");
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomArticle,DescriptionArticle,QtiteArticle")] Article article)
        {
            if (ModelState.IsValid)
            {
                _context.Add(article);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomArticle,DescriptionArticle,QtiteArticle")] Article article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Articles == null)
            {
                return Problem("Entity set 'DbContextMag.Articles'  is null.");
            }
            var article = await _context.Articles.FindAsync(id);
            if (article != null)
            {
                _context.Articles.Remove(article);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
          return (_context.Articles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Asp.net Core MVC GestionMag/Controllers/HomeController.cs
using Asp.net_Core_MVC_GestionMag.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Asp.net_Core_MVC_GestionMag.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Asp.net Core MVC GestionMag/Views/Article/Index.cshtml
@model IEnumerable<Article>
@{
    ViewData["Title"] = "Index";
}

<h1>La listes des articles</h1>
<table class="table table-bordered table-striped">
    <thead>
        <tr>

            <th>Numéro d'identifiant de l'article</th>
            <th>Nom de l'article</th>
            <th>Description de l'article</th>
            <th>Quantité de l'article</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.NomArticle</td>
                <td>@item.DescriptionArticle</td>
                <td>@item.QtiteArticle</td>
            </tr>
        }
    </tbody>
</table>

Asp.net Core MVC GestionMag/Views/Articles/Create.cshtml
@model Asp.net_Core_MVC_GestionMag.Models.Article

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomArticle" class="control-label"></label>
                <input asp-for="NomArticle" class="form-control" />
                <span asp-validation-for="NomArticle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionArticle" class="control-label"></label>
                <input asp-for="DescriptionArticle" class="form-control" />
                <span asp-validation-for="DescriptionArticle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QtiteArticle" class="control-label"></label>
                <input asp-for="QtiteArticle" class="form-control" />
                <span asp-validation-for="QtiteArticle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Asp.net Core MVC GestionMag/Views/Articles/Delete.cshtml
@model Asp.net_Core_MVC_GestionMag.Models.Article

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomArticle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomArticle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionArticle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionArticle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QtiteArticle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QtiteArticle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Asp.net Core MVC GestionMag/Views/Articles/Details.cshtml
@model Asp.net_Core_MVC_GestionMag.Models.Article

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomArticle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomArticle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionArticle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionArticle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QtiteArticle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QtiteArticle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Asp.net Core MVC GestionMag/Views/Articles/Edit.cshtml
@model Asp.net_Core_MVC_GestionMag.Models.Article

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NomArticle" class="control-label"></label>
                <input asp-for="NomArticle" class="form-control" />
                <span asp-validation-for="NomArticle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionArticle" class="control-label"></label>
                <input asp-for="DescriptionArticle" class="form-control" />
                <span asp-validation-for="DescriptionArticle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QtiteArticle" class="control-label"></label>
                <input asp-for="QtiteArticle" class="form-control" />
                <span asp-validation-for="QtiteArticle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Asp.net Core MVC GestionMag/Views/Articles/Index.cshtml
@model IEnumerable<Asp.net_Core_MVC_GestionMag.Models.Article>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomArticle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescriptionArticle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QtiteArticle)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomArticle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescriptionArticle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QtiteArticle)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Asp.net Core MVC GestionMag/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.net Core MVC GestionMag/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp.net_Core_MVC_GestionMag</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asp.net_Core_MVC_GestionMag.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Store management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Article</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">All Article</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Store management - By  <a href="https://twitter.com/bakarysylla58">&commat;SYLLA </a> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>